In [6]:
from tree import Tree, Forest

generate_configs = {
    "seed": 1,
    "gp_len": 64,
    "input_len": 3,
    "output_len": 1,
    "const_prob": 0.5,
    "out_prob": 0.5,
    "func_prob": {"+": 0.25, "-": 0.25, "*": 0.25, "/": 0.25},
    "max_layer_cnt": 5,
    "layer_leaf_prob": 0.2,
    "const_range": (-1, 1),
    "sample_cnt": 8
}

tree = Forest.random_generate(pop_size=10, **generate_configs)

SyntaxError: invalid character '🌳' (U+1F333) (280915712.py, line 17)

In [2]:
print(forest)

[
  x[0] , 
  0.70 , 
  / / * + - 0.70 0.70 + x[0] 0.70 / - 0.70 -0.43 + 0.22 0.22 * / - 0.91 x[0] / -0.62 x[0] / / -0.43 x[0] + 0.22 -0.43 + -0.43 / + - x[0] x[2] * x[0] x[2] x[1] , 
  * x[0] * * + 0.70 - x[2] -0.22 - / x[0] x[0] + x[0] -0.22 / * / x[2] -0.62 x[2] * - x[1] x[0] x[2] , 
  + - - 0.91 -0.22 -0.43 + * * * x[1] x[2] + 0.70 x[2] + - -0.22 x[1] * x[2] x[2] / + * 0.22 0.91 + -0.62 x[0] x[2] , 
  + - * - - 0.70 x[2] + -0.62 0.22 / + x[1] -0.43 -0.62 + + + 1.00 x[0] / x[2] 1.00 - + 0.70 x[2] 0.70 - / 1.00 - / x[1] 0.91 1.00 * / * -0.43 1.00 - x[0] 0.91 + / x[1] x[2] x[0] , 
  * / - / / -0.22 1.00 / x[2] x[2] - x[1] * x[2] x[0] * + - 0.22 x[2] - x[1] x[2] - + -0.62 x[0] + x[0] 0.04 * * - * x[2] x[2] -0.62 * + x[0] x[0] * x[2] x[1] - / * -0.43 0.70 / 1.00 x[0] / -0.62 0.70 , 
  x[0] , 
  -0.43 , 
  * / / - 0.04 -0.43 x[0] / / / 0.91 x[1] * x[0] 0.70 0.91 / / x[0] -0.62 - * * 1.00 x[2] * x[1] -0.43 + x[1] / 0.70 x[1] , 
]


In [3]:
import torch
tree = forest[0]
res = tree.forward(torch.Tensor([1, 2, 3]))
print(res)

tensor([1.], device='cuda:0')


In [4]:
res = forest.forward(torch.ones(10, 3))

In [5]:
res

tensor([[ 1.0000e+00],
        [ 6.9722e-01],
        [ 2.4932e+01],
        [-4.2417e+04],
        [ 1.7681e+00],
        [ 1.5527e+01],
        [-8.2777e-01],
        [ 1.0000e+00],
        [-4.3255e-01],
        [ 2.4820e-01]], device='cuda:0')

In [3]:
import torch
a = torch.tensor([1,2,3,4,5,6,7,8,9])
bool_indices = a % 2 == 0

a, bool_indices

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([False,  True, False,  True, False,  True, False,  True, False]))

In [6]:
b = a[bool_indices] + 100
b

tensor([102, 104, 106, 108])

In [7]:
a[bool_indices] = b

In [8]:
a

tensor([  1, 102,   3, 104,   5, 106,   7, 108,   9])

In [16]:
import torch
a = torch.tensor([1,2,3,4,5,6,7,8,9], dtype=torch.int16, device="cuda")
torch.gather(a, 0, torch.tensor([1 ,2, 3], dtype=torch.int64, device="cuda"))

RuntimeError: "cuda_scatter_gather_base_kernel_func" not implemented for 'UInt16'

In [1]:
import sys
print(sys.getdefaultencoding())  # 应该输出 'utf-8'

utf-8


In [3]:
"&#128512; &#128526; &#128640; &#10084;"

'&#128512; &#128526; &#128640; &#10084;'

In [5]:
a = "😀 😎 🚀 ❤️"
a

'😀 😎 🚀 ❤️'

In [7]:
code = "😀😎🚀❤️ = 12342435"
exec(code)

SyntaxError: invalid character '😀' (U+1F600) (<string>, line 1)